/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nic;

/**
 *
 * @author User
 */
public class Nic_interface extends javax.swing.JFrame {

    /**
     * Creates new form Nic_interface
     */
    public Nic_interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("enter your  Nic");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("click me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("birth day");

        lbl2.setText("DD/MM/YY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str1 = jTextField1.getText();
        String str2 = "";
        int str3 = 0;
        int str4 = 0;
        String str5 = "";
        if (str1.length() == 10) {
            str2 = str1.substring(0, 2);
            str3 = Integer.parseInt(str1.substring(2, 5));
            if (str3 <= 500) {
                if (str3 <= 31) {
                    str4 = str3;
                    str5 = "01";

                } else if (str3 <= 60) {
                    str4 = str3 - 31;
                    str5 = "02";
                } else if (str3 <= 91) {
                    str4 = str3 - 60;
                    str5 = "03";
                } else if (str3 <= 121) {
                    str4 = str3 - 91;
                    str5 = "04";
                } else if (str3 <= 152) {
                    str4 = str3 - 121;
                    str5 = "05";
                } else if (str3 <= 182) {
                    str4 = str3 - 152;
                    str5 = "06";
                } else if (str3 <= 213) {
                    str4 = str3 - 182;
                    str5 = "07";
                } else if (str3 <= 244) {
                    str4 = str3 - 213;
                    str5 = "08";
                } else if (str3 <= 274) {
                    str4 = str3 - 244;
                    str5 = "09";
                } else if (str3 <= 305) {
                    str4 = str3 - 274;
                    str5 = "10";
                } else if (str3 <= 335) {
                    str4 = str3 - 305;
                    str5 = "11";
                } else if (str3 <= 366) {
                    str4 = str3 - 335;
                    str5 = "12";
                } else {
                    lbl2.setText("invalied input");
                }
            } else {
                if (str3 <= 531) {
                    str4 = str3;
                    str5 = "01";

                } else if (str3 <= 560) {
                    str4 = str3 - 531;
                    str5 = "02";
                } else if (str3 <= 591) {
                    str4 = str3 - 560;
                    str5 = "03";
                } else if (str3 <= 621) {
                    str4 = str3 - 591;
                    str5 = "04";
                } else if (str3 <= 652) {
                    str4 = str3 - 621;
                    str5 = "05";
                } else if (str3 <= 682) {
                    str4 = str3 - 652;
                    str5 = "06";
                } else if (str3 <= 713) {
                    str4 = str3 - 682;
                    str5 = "07";
                } else if (str3 <= 744) {
                    str4 = str3 - 713;
                    str5 = "08";
                } else if (str3 <= 774) {
                    str4 = str3 - 744;
                    str5 = "09";
                } else if (str3 <= 805) {
                    str4 = str3 - 774;
                    str5 = "10";
                } else if (str3 <= 835) {
                    str4 = str3 - 805;
                    str5 = "11";
                } else if (str3 <= 866) {
                    str4 = str3 - 835;
                    str5 = "12";
                } else {
                    lbl2.setText("invalied input");
                }
                lbl2.setText(str4 + "/" + str5 + "/" + str2);
            }

        } else if (str1.length() == 12) {
            str2 = str1.substring(2, 4);
            str3 = Integer.parseInt(str1.substring(4, 7));
            if (str3 <= 500) {
                if (str3 <= 31) {
                    str4 = str3;
                    str5 = "01";

                } else if (str3 <= 60) {
                    str4 = str3 - 31;
                    str5 = "02";
                } else if (str3 <= 91) {
                    str4 = str3 - 60;
                    str5 = "03";
                } else if (str3 <= 121) {
                    str4 = str3 - 91;
                    str5 = "04";
                } else if (str3 <= 152) {
                    str4 = str3 - 121;
                    str5 = "05";
                } else if (str3 <= 182) {
                    str4 = str3 - 152;
                    str5 = "06";
                } else if (str3 <= 213) {
                    str4 = str3 - 182;
                    str5 = "07";
                } else if (str3 <= 244) {
                    str4 = str3 - 213;
                    str5 = "08";
                } else if (str3 <= 274) {
                    str4 = str3 - 244;
                    str5 = "09";
                } else if (str3 <= 305) {
                    str4 = str3 - 274;
                    str5 = "10";
                } else if (str3 <= 335) {
                    str4 = str3 - 305;
                    str5 = "11";
                } else if (str3 <= 366) {
                    str4 = str3 - 335;
                    str5 = "12";
                } else {
                    lbl2.setText("invalied input");
                }
            } else {
                if (str3 <= 531) {
                    str4 = str3;
                    str5 = "01";

                } else if (str3 <= 560) {
                    str4 = str3 - 531;
                    str5 = "02";
                } else if (str3 <= 591) {
                    str4 = str3 - 560;
                    str5 = "03";
                } else if (str3 <= 621) {
                    str4 = str3 - 591;
                    str5 = "04";
                } else if (str3 <= 652) {
                    str4 = str3 - 621;
                    str5 = "05";
                } else if (str3 <= 682) {
                    str4 = str3 - 652;
                    str5 = "06";
                } else if (str3 <= 713) {
                    str4 = str3 - 682;
                    str5 = "07";
                } else if (str3 <= 744) {
                    str4 = str3 - 713;
                    str5 = "08";
                } else if (str3 <= 774) {
                    str4 = str3 - 744;
                    str5 = "09";
                } else if (str3 <= 805) {
                    str4 = str3 - 774;
                    str5 = "10";
                } else if (str3 <= 835) {
                    str4 = str3 - 805;
                    str5 = "11";
                } else if (str3 <= 866) {
                    str4 = str3 - 835;
                    str5 = "12";
                } else {
                    lbl2.setText("invalied input");
                }
                lbl2.setText(str4 + "/" + str5 + "/" + str2);
            }
        } else {
            lbl2.setText("invalied input");
    }//GEN-LAST:event_jButton1ActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nic_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nic_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nic_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nic_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nic_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl2;
    // End of variables declaration//GEN-END:variables
}
